tiymce_contentcss_new:
    path: /tinymce/content_css/new
    defaults: { _controller: TinymceBundle:Css:new }

tiymce_contentcss_change:
    path: /tinymce/content_css/change
    defaults: { _controller: TinymceBundle:Css:change }

tiymce_data:
    path: /tinymce/data/link
    defaults: { _controller: TinymceBundle:Data:link }
