parameters:
    phlexible_tinymce.settings: ~
    phlexible_tinymce.setup: ~

services:
    # event listeners
    phlexible_tinymce.listener.view_frame:
        class: Phlexible\Bundle\TinymceBundle\EventListener\ViewFrameListener
        arguments:
            - "@templating.helper.assets"
            - "%kernel.debug%"
            - "%phlexible_tinymce.settings%"
            - "%phlexible_tinymce.setup%"
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.view_frame, method: onViewFrame}

    # fields
    phlexible_tinymce.field.editor:
        class: Phlexible\Bundle\TinymceBundle\Field\EditorField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: editor}
