parameters:
    phlexible_tinymce.settings: ~
    phlexible_tinymce.setup: ~

services:
    # asset providers
    phlexible_tinymce.asset_provider:
        class: Phlexible\TinymceBundle\AssetProvider\TinymceAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # event listeners
    phlexible_tinymce.listener.view_frame:
        class: Phlexible\TinymceBundle\EventListener\ViewFrameListener
        arguments: [%kernel.debug%, %phlexible_tinymce.settings%, %phlexible_tinymce.setup%]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.view_frame, method: onViewFrame}

    # fields
    phlexible_tinymce.field.editor:
        class: Phlexible\TinymceBundle\Field\EditorField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: editor}
