parameters:
    tinymce.settings: ~
    tinymce.setup: ~

services:
    # fields
    tinymce.field.editor:
        class: Phlexible\TinymceComponent\Field\EditorField
        tags:
            - {name: "elementtypes.field", alias: editor}

    # listeners
    tinymce.listener.viewframe:
        class: Phlexible\TinymceComponent\Listener\ViewFrameListener
        arguments: ["%kernel.debug%", "%tinymce.settings%", "%tinymce.setup%"]
        tags:
            - {name: "kernel.event_listener", event: gui.view_frame, method: onViewFrame}

    # assets
    tinymce.asset.scripts:
        class: Phlexible\TinymceComponent\Asset\ScriptCollection
        arguments: ["%tinymce.asset.script_path%/"]
        tags:
            - {name: "asset.script"}
