parameters:
    tinymce.settings: ~
    tinymce.setup: ~

services:
    # asset providers
    tinymce.asset_provider:
        class: Phlexible\TinymceBundle\AssetProvider\TinymceAssetProvider
        arguments: [@file_locator]
        tags:
            - {name: "asset.provider"}

    # event listeners
    tinymce.listener.viewframe:
        class: Phlexible\TinymceBundle\EventListener\ViewFrameListener
        arguments: ["%kernel.debug%", "%tinymce.settings%", "%tinymce.setup%"]
        tags:
            - {name: "kernel.event_listener", event: gui.view_frame, method: onViewFrame}

    # fields
    tinymce.field.editor:
        class: Phlexible\TinymceBundle\Field\EditorField
        tags:
            - {name: "elementtypes.field", alias: editor}
