image: swentz/build:5.6

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer --version
          - composer install
          - php -dzend_extension=xdebug.so vendor/bin/phpunit -v --exclude-group functional --coverage-clover=coverage.xml
